### ISSUE TITLE
django rest framework + jwt

### ISSUE THREAD

**Issue by theambitious** [st4lk/django-rest-social-auth#15]
A post with the appropriate data returns the following AssertionError 

"POST /api/login/social/jwt/facebook/ HTTP/1.1" 500 111962
AssertionError: 'SocialJWTOnlyAuthView' should either include a `queryset` attribute, or override the `get_queryset()` method.

Does the SocialJWTOnlyAuthView work out of the box with DRF + jwt? I'm using the Django default user model, so I am not explicitly defining settings.AUTH_USER_MODEL. Might this be part of the problem?

Thank you

**Comment by st4lk** [comment]
Yes, i suppose it is needed to explicitly define the model in view, like [this](https://github.com/st4lk/django-rest-social-auth/blob/master/example_project/users/views.py#L40).

I think it will be good to include default user model for a view by default in this package.

**Comment by st4lk** [comment]
Ah no, it **should** work out of the box. There is no need to define the model for this view.

The `get_object` method is completely overridden in `SocialJWTOnlyAuthView` (since it subclass `BaseSocialAuthView`) and it doesn't call nor `super().get_object` nor `super().get_queryset` (where mentioned error can be raised).

Please precise following points:
- what version of this package are you using?
- do you subclass the SocialJWTOnlyAuthView somewhere in your code?

**Comment by st4lk** [comment]
I guess this issue is also related to #21

Looks like exception is the same

**Comment by st4lk** [comment]
All work will be in issue #20
