### ISSUE TITLE
Facebook (and all others) 400 Bad Request

### ISSUE THREAD

**Issue by taime** [st4lk/django-rest-social-auth#56]
All've been made exactly like in installation docs. 
Get 400 Bad Request for facebook

**input:**
`{
      "provider": "facebook",
      "code": "my-facebook-user-token"
  }`
**output - 400 BAD REQUEST:**
`Authentication process canceled; ; {'error': {'type': 'OAuthException', 'code': 100, 'message': 'Invalid verification code format.', 'fbtrace_id': 'D3LTueyhCdD'}}`

**Comment by SalunMarvin** [comment]
You're using the Access Token, not the code. I'm having the same issue, I can't find the code on the Redirect URL. :(

**Comment by KhanMaytok** [comment]
Where to find the code?

**Comment by st4lk** [comment]
@taime 
Please try [example project](https://github.com/st4lk/django-rest-social-auth#example). It should work.
If not, you can submit a new issue or reopen this one.

**Comment by birgert** [comment]
@SalunMarvin Did you ever figure out how to get the "code"?
My frontend receives the "accessToken" from Facebook. When providing this to the api endpoint where it expects "code", it just results in the same error as reported here before:

**Comment by fonar** [comment]
@taime @birgert have you found a solution?
@st4lk i'm having the same issue

**Comment by birgert** [comment]
@fonar, I eventually switched to using Amazon AWS Cognito instead for all my user registration and authentication. All I do in django now is verify the Cognito token validity before processing requests.

It's unfortunate how there's no kind off decent all in one for django on this topic. In the end you end up customizing all these packages to integrate things like google recaptcha, then you find simplejwt doesn't work with _django-rest-auth_, it only uses the old _djangorestframework-jwt_ which is no longer maintained, leading to further customization. 
This issue thread here only refers to the example project, simply assuming that everyone knows how to get that code instead of an access_token, I never found a way to get the code as a response from FB, hence why I abandoned using all this. 

It really is just too bad as a lot of these packages have good features, but after a while they don't get expanded or maintained anymore, leading to extensive customization and having bits and pieces all over the place.
