### ISSUE TITLE
why not sending error messages back with the 400 response?

### ISSUE THREAD

**Issue by macolo** [st4lk/django-rest-social-auth#64]
Like, here: https://github.com/st4lk/django-rest-social-auth/blob/master/rest_social_auth/views.py#L183

Status Quo makes it impossible for the frontend to figure out what went wrong?

**Comment by st4lk** [comment]
As far as I remember, the error can contain some information that is not always safe to send it to front-end.

**Comment by macolo** [comment]
Hm in that case I suggest to add at least the error type, for example `redirect_uri_mismatch`

**Comment by gustavengstrom** [comment]
I am testing out django-rest-auth but I am recieving a 400 error instead of token back following the JWT example in the readme. My test case is facebook login. I am following the example on https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/ to generate a authorization code and when testing it out by exchanging it for an access token using the included examples on facebook all works well.... 

However, when using the same auth code using my rest api https://localhost:9999/api/login/social/jwt/, {"code": "AQC4Mab9rWU....."}, to  I get a 400 response...

Any idea what is going on here??

**Comment by st4lk** [comment]
@macolo 
It'll be a good improvement. Not sure I'll have time for this in near future. But if you'd like to take part in this project - you are welcome.

**Comment by st4lk** [comment]
@gustavengstrom 
Please try [example project](https://github.com/st4lk/django-rest-social-auth#example).

**Comment by st4lk** [comment]
@macolo 
BTW, there is an existing open issue: https://github.com/st4lk/django-rest-social-auth/issues/26
So I'm closing this as a duplicate.
